### ISSUE TITLE
Great work 🙌

### ISSUE THREAD

**Issue by lissy93** [Just-Moh-it/Just-Moh-it#2]
Heya Mohit
Just wanted to drop you a line, and say keep up the great work! The tools you've build are really awesome, and I'd never have guessed you were only 17 from the quality of your work - you've got a bright future ahead!!

I've sent you a small sponsership, and if you ever need anything, feel free to reach out :)
Alicia

**Comment by Just-Moh-it** [comment]
Hey Alicia,

Thank you so much for your kind words and for your sponsorship. I am truly grateful and overwhelmed by your support. It's great to hear that my work is appreciated and that you think I have a bright future ahead of me. Although I am only 17, I am passionate about software development and strive to improve my skills and learn new things.

Your offer to help if ever needed is greatly appreciated. Your support means a lot and I will definitely reach out if the need arises.

Thank you again for your kind words and for your support. It is truly appreciated! ☺️
